from __future__ import annotations

from copy import deepcopy
from typing import Any


SYSTEM_DEBUG_REGISTRY_VERSION = "v1"


DEFAULT_CHAIN_REGISTRY: list[dict[str, Any]] = [
    {
        "chain_name": "source_discovery_review",
        "category": "material_line",
        "maturity_level": "Level 3",
        "has_contract": True,
        "has_checkpoint": False,
        "has_retry": False,
        "has_resume": False,
        "has_state_file": False,
        "has_stage_report": True,
        "has_diff_or_backtest": False,
        "has_patch_or_bundle": False,
        "has_human_review_gate": True,
        "input_artifacts": [
            "gold_reconstruction_results.jsonl",
            "source_discovery_queries.jsonl",
            "source_candidate_results.jsonl",
        ],
        "output_artifacts": [
            "source_candidate_review.json",
            "source_seed_registry.jsonl",
            "crawl_seed_manifest.json",
            "source_candidate_human_review_report.md",
        ],
        "dependency_on": ["gold_reconstruction", "source_candidate_search"],
        "blocked_by": ["missing_source_candidate_results", "missing_human_review_decisions"],
        "artifact_patterns": [
            "source_candidate_review.json",
            "source_seed_registry.jsonl",
            "crawl_seed_manifest.json",
            "source_candidate_human_review_report.md",
            "source_discovery_queries.jsonl",
            "source_candidate_results.jsonl",
            "source_candidate_summary.json",
        ],
        "notes": "材料来源候选和用户 review 决策链；seed 仍是 seed_only，不确认原文。",
    },
    {
        "chain_name": "material_protocol_split_pipeline",
        "category": "material_line",
        "maturity_level": "Level 3",
        "has_contract": True,
        "has_checkpoint": True,
        "has_retry": True,
        "has_resume": True,
        "has_state_file": True,
        "has_stage_report": True,
        "has_diff_or_backtest": True,
        "has_patch_or_bundle": False,
        "has_human_review_gate": True,
        "input_artifacts": [
            "material_protocol_draft_input_digest.json",
            "system_alignment_findings.json",
            "source_seed_registry.jsonl",
        ],
        "output_artifacts": [
            "pipeline_state.json",
            "pipeline_stage_report.json",
            "pipeline_stage_report.md",
            "stages/01_material_evidence_map.json",
            "stages/02_material_semantic_requirements_draft.json",
            "stages/03_material_card_draft.json",
            "stages/04_material_line_prompt_assets_draft.json",
            "stages/05_material_quality_regression_draft.json",
            "stages/06_material_bridge_mapping_draft.json",
        ],
        "dependency_on": ["source_discovery_review"],
        "blocked_by": ["provider_error", "validation_error", "missing_evidence_digest"],
        "artifact_patterns": [
            "pipeline_state.json",
            "pipeline_stage_report.json",
            "pipeline_stage_report.md",
            "material_protocol_split_pipeline_report.md",
            "01_material_evidence_map.json",
            "02_material_semantic_requirements_draft.json",
            "03_material_card_draft.json",
            "04_material_line_prompt_assets_draft.json",
            "05_material_quality_regression_draft.json",
            "06_material_bridge_mapping_draft.json",
            "material_quality_regression_draft.json",
            "material_bridge_mapping_draft.json",
        ],
        "notes": "当前最接近 multi-like 调试流水线的材料链；具备 checkpoint/retry/resume/stage report。",
    },
    {
        "chain_name": "material_cleaning_slicing_chain",
        "category": "material_line",
        "maturity_level": "Level 0",
        "has_contract": False,
        "has_checkpoint": False,
        "has_retry": False,
        "has_resume": False,
        "has_state_file": False,
        "has_stage_report": False,
        "has_diff_or_backtest": False,
        "has_patch_or_bundle": False,
        "has_human_review_gate": True,
        "input_artifacts": [
            "source_body_fetch_results.jsonl",
            "source_gold_alignment_results.jsonl",
        ],
        "output_artifacts": [
            "material_cleaning_recipe_draft.json",
            "material_span_candidates.jsonl",
            "material_quality_stats.json",
        ],
        "dependency_on": ["source_discovery_review"],
        "blocked_by": ["missing_source_body_fetch", "missing_source_gold_alignment", "missing_human_crawl_approval"],
        "artifact_patterns": [
            "material_cleaning_recipe_draft.json",
            "material_span_candidates.jsonl",
            "material_quality_stats.json",
            "material_quality_report.md",
        ],
        "notes": "清洗/切片/选段链目前主要是文档级规划，尚无正式 runtime；登记用于总控台显示缺口，不表示已实现。",
    },
    {
        "chain_name": "question_protocol_patch_chain",
        "category": "question_protocol_line",
        "maturity_level": "Level 3",
        "has_contract": True,
        "has_checkpoint": False,
        "has_retry": False,
        "has_resume": False,
        "has_state_file": False,
        "has_stage_report": True,
        "has_diff_or_backtest": True,
        "has_patch_or_bundle": True,
        "has_human_review_gate": True,
        "input_artifacts": [
            "axis_confirmation.json",
            "formal_patch_draft.json",
            "formal_writeback_plan.json",
        ],
        "output_artifacts": [
            "formal_patch_draft.json",
            "formal_writeback_plan.json",
            "formal_writeback_diff.md",
            "formal_writeback_manifest.json",
            "formal_writeback_regression_report.json",
        ],
        "dependency_on": ["leaf_pre_distill"],
        "blocked_by": ["missing_axis_confirmation", "missing_approval", "regression_failed"],
        "artifact_patterns": [
            "axis_confirmation.json",
            "formal_patch_draft.json",
            "formal_writeback_plan.json",
            "formal_writeback_diff.md",
            "formal_writeback_manifest.json",
            "formal_writeback_regression_report.json",
        ],
        "notes": "题卡/提示词/validator 候选 patch 与受控写回链；不是自动正式化。",
    },
    {
        "chain_name": "question_generation_runtime",
        "category": "generation_line",
        "maturity_level": "Level 2",
        "has_contract": True,
        "has_checkpoint": False,
        "has_retry": True,
        "has_resume": False,
        "has_state_file": False,
        "has_stage_report": False,
        "has_diff_or_backtest": True,
        "has_patch_or_bundle": False,
        "has_human_review_gate": True,
        "input_artifacts": ["QuestionGenerateRequest", "question_card", "material_selection"],
        "output_artifacts": ["QuestionGenerationBatchResponse", "runtime_event", "review_action"],
        "dependency_on": ["question_protocol_patch_chain", "material_protocol_split_pipeline"],
        "blocked_by": ["unmapped_business_subtype", "validator_failure", "material_bridge_unavailable"],
        "artifact_patterns": [
            "generation_trial_result.json",
            "runtime_event.json",
            "question_generation_report.md",
            "distill_run_generation_snapshot.json",
        ],
        "notes": "生题主链有局部 orchestrator、validator、review/action 和 runtime observer；没有 durable pipeline state。",
    },
    {
        "chain_name": "difficulty_control_chain",
        "category": "difficulty_line",
        "maturity_level": "Level 2",
        "has_contract": True,
        "has_checkpoint": False,
        "has_retry": False,
        "has_resume": False,
        "has_state_file": False,
        "has_stage_report": False,
        "has_diff_or_backtest": True,
        "has_patch_or_bundle": True,
        "has_human_review_gate": True,
        "input_artifacts": ["generation_request", "generated_item", "gold_reference"],
        "output_artifacts": [
            "difficulty_projection",
            "actual_difficulty_assessment",
            "difficulty_diff",
            "difficulty_calibration_patch",
        ],
        "dependency_on": ["question_generation_runtime", "truth_gold_regression"],
        "blocked_by": ["missing_gold_reference", "missing_generated_item", "missing_backtest_runner"],
        "artifact_patterns": [
            "difficulty_projection.json",
            "actual_difficulty_assessment.json",
            "difficulty_diff.json",
            "difficulty_calibration_patch.json",
            "difficulty_backtest_report.md",
        ],
        "notes": "有 projection/assessment/diff/calibration 服务；缺系统级 durable backtest runner。",
    },
    {
        "chain_name": "distillation_runtime_workbench",
        "category": "distillation_line",
        "maturity_level": "Level 3-",
        "has_contract": True,
        "has_checkpoint": True,
        "has_retry": False,
        "has_resume": False,
        "has_state_file": True,
        "has_stage_report": False,
        "has_diff_or_backtest": True,
        "has_patch_or_bundle": True,
        "has_human_review_gate": True,
        "input_artifacts": [
            "distillation_input_packet",
            "distill_dataset",
            "distill_session",
            "distill_run",
        ],
        "output_artifacts": [
            "distillation_result_packet",
            "distillation_diff_report",
            "distill_promotion_bundle",
            "promotion_bundle_artifact",
        ],
        "dependency_on": ["question_generation_runtime", "difficulty_control_chain"],
        "blocked_by": ["missing_review", "missing_patch_for_target", "failed_trial_run"],
        "artifact_patterns": [
            "distillation_result_packet.json",
            "distillation_diff_report.md",
            "distill_promotion_bundle.json",
            "promotion_bundle.json",
            "distill_run_detail.json",
        ],
        "notes": "有 dataset/session/run/review/patch/promote 和 promotion bundle；缺通用 checkpoint/retry/resume。",
    },
    {
        "chain_name": "truth_gold_regression",
        "category": "distillation_line",
        "maturity_level": "Level 3",
        "has_contract": True,
        "has_checkpoint": False,
        "has_retry": False,
        "has_resume": False,
        "has_state_file": True,
        "has_stage_report": True,
        "has_diff_or_backtest": True,
        "has_patch_or_bundle": False,
        "has_human_review_gate": True,
        "input_artifacts": ["samples.jsonl", "gold_reconstruction_results.jsonl", "generated_items.jsonl"],
        "output_artifacts": [
            "truth_gold_split_manifest.json",
            "truth_gold_regression_results.json",
            "truth_gold_regression_report.md",
        ],
        "dependency_on": ["gold_reconstruction"],
        "blocked_by": ["missing_gold_reconstruction", "missing_generated_items_for_comparison"],
        "artifact_patterns": [
            "truth_gold_split_manifest.json",
            "truth_gold_regression_results.json",
            "truth_gold_regression_report.md",
        ],
        "notes": "真题 gold 分集与 generated comparison 框架；报告不是 formal approval。",
    },
]


def default_chain_registry() -> list[dict[str, Any]]:
    return deepcopy(DEFAULT_CHAIN_REGISTRY)


def filter_registry(chains: list[dict[str, Any]], selected_names: list[str] | None = None) -> list[dict[str, Any]]:
    if not selected_names:
        return deepcopy(chains)
    wanted = {name.strip() for name in selected_names if name.strip()}
    return [deepcopy(chain) for chain in chains if chain.get("chain_name") in wanted]


def registry_by_name(chains: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {str(chain.get("chain_name")): chain for chain in chains}
